;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    ____        __      __              
;;	   / __ \____  / /_  __/ /_  ____ ______
;;	  / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;	 / ____/ /_/ / / /_/ / /_/ / /_/ / /    
;;	/_/    \____/_/\__, /_.___/\__,_/_/     
;;	              /____/                    
;;
;; Created By Aditya Shakya @adi1090x
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

bg = #000000
fg = #FFFFFF
fg-alt = #A9ABB0
clear = #00000000

acolor = #FFFFFF
curgent = #B30a07
coccupied = #42A5F5

# shade1 = #3E2723
# shade2 = #4E342E
# shade3 = #5D4037
# shade4 = #6D4C41
# shade5 = #795548
# shade6 = #8D6E63
# shade7 = #A1887F
# shade8 = #BCAAA4
# txt = #2C2C2C
# 
# ## Material Colors
# 
# red = #e53935
# pink = #d81b60
# purple = #8e24aa
# deep-purple = #5e35b1
# indigo = #3949ab
# blue = #1e88e5
# light-blue = #039be5
# cyan = #00acc1
# teal = #00897b
# green = #43a047
# light-green = #7cb342
# lime = #c0ca33
# yellow = #fdd835
# amber = #ffb300
# orange = #fb8c00
# deep-orange = #f4511e
# brown = #6d4c41
# grey = #757575
# blue-gray = #546e7a
# kindadark = #aa1c1c1c

;==========================================================

[bar/main]
width = 100%
height = 25
offset-x = 0%
offset-y = 0%
bottom = false
fixed-center = true
line-size = 2
# padding-left = 1 
background = ${color.bg}
foreground = ${color.fg}
# border-size = 8
# border-color = ${color.clear}
# radius = 8

;==========================================================

font-0 = "Fantasque Sans Mono:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:pixelsize=11;3"

;==========================================================

enable-ipc = true
cursor-click = pointer

scroll-up = #i3.next
scroll-down = #i3.prev

;== Module Location ========================================================

modules-left = i3 
modules-center = title
modules-right = volume network date powermenu
 
;== Modules ========================================================

[module/title]
type = internal/xwindow
format-padding = 2
label-maxlen = 75

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 3
label-mode-foreground = #fff
label-mode-background = #aa000000

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = #55ca9945
# label-focused-background = ${color.kindadark}
# label-focused-underline= #ffffff
label-focused-padding = 2px 

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-background = ${color.bg}
label-unfocused-padding = ${self.label-focused-padding}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${self.label-focused-background}
# label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${color.curgent}
label-urgent-padding = ${self.label-focused-padding} 

;==========================================================

[module/mpd]
type = internal/mpd
format-online = <toggle> <label-song> 
;format-online =  <label-song> 
;alt icons =   
format-online-background = ${color.bg}
format-online-foreground = ${color.txt}
format-online-padding = 2

icon-play = 喇
icon-pause = 

label-song-maxlen = 25
label-song-ellipsis = true

;==========================================================

[module/battery]
type = internal/battery
full-at = 99
time-format = %H:%M
battery = BAT1
adapter = AC
format-charging = <animation-charging> <label-charging>
format-charging-background = ${color.bg}
format-charging-padding = 2
label-charging = %percentage%%
format-discharging = <ramp-capacity> <label-discharging>
format-discharging-background = ${color.bg}
format-discharging-padding = 2
label-discharging = %percentage%%
format-full = <label-full>

format-full-prefix = " "
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

ramp-capacity-0-foreground = ${color.red}
ramp-capacity-1-foreground = ${color.red}
ramp-capacity-foreground   = ${color.fg}
bar-capacity-width = 10

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 

animation-charging-framerate = 750

[module/volume]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2
format-volume-background = ${color.bg}
label-volume = %percentage%%
label-muted = "婢"
label-muted-background = ${color.bg}
label-muted-padding = 2

ramp-volume-0 = 奄
ramp-volume-1 = 奄
ramp-volume-2 = 奔
ramp-volume-3 = 奔
ramp-volume-4 = 墳
ramp-volume-5 = 墳
ramp-volume-6 = 墳

[module/network]
type = custom/script
exec = ~/.config/polybar/scripts/check-network
format-background = ${color.bg}
format-padding = 2
click-left = bash "./rofi-wifi-menu/rofi-wifi-menu.sh" 
click-right = bash "./rofi-wifi-menu/rofi-wifi-menu.sh"
tail = true

[module/date]
type = internal/date
interval = 30
label =  %time%
label-padding-left = 2
label-padding-right = 3
label-background = ${color.bg}
time =  %H:%M 
time-alt =  %d/%m/%Y

[module/powermenu]
type = custom/text
content = 襤
content-padding = 2 
content-background = #55ca9945
content-foreground = #ffffff
click-left = rofi -show power-menu -modi power-menu:rofi-power-menu -font 'FiraCode NF 10' -width 20 -lines 6 -xoffset -27 -yoffset 60 -location 3  
click-right = ~/.config/polybar/scripts/sysmenu
;== EOF ========================================================
